export const DOCTOR_AVAILABILITY = [
  {
    timezone: 'US/Eastern',
    startHour: 10,
    endHour: 17,
    durationMinutes: 30,
    eveningStartHour: 20,
    eveningStartMinute: 30,
  },
  {
    timezone: 'US/Central',
    startHour: 10,
    endHour: 17,
    durationMinutes: 30,
    eveningStartHour: 20,
    eveningStartMinute: 30,
  },
  {
    timezone: 'US/Mountain',
    startHour: 10,
    endHour: 17,
    durationMinutes: 30,
    eveningStartHour: 20,
    eveningStartMinute: 30,
  },
  {
    timezone: 'US/Pacific',
    startHour: 10,
    endHour: 17,
    durationMinutes: 30,
    eveningStartHour: 20,
    eveningStartMinute: 30,
  },
  {
    timezone: 'Europe/London',
    startHour: 10,
    endHour: 17,
    durationMinutes: 30,
    eveningStartHour: 20,
    eveningStartMinute: 30,
  },
  {
    timezone: 'Europe/Paris',
    startHour: 10,
    endHour: 17,
    durationMinutes: 30,
    eveningStartHour: 20,
    eveningStartMinute: 30,
  },
  {
    timezone: 'Asia/Kolkata',
    startHour: 10,
    endHour: 17,
    durationMinutes: 30,
    eveningStartHour: null,
    eveningStartMinute: null,
  },
  {
    timezone: 'Asia/Tokyo',
    startHour: 10,
    endHour: 17,
    durationMinutes: 30,
    eveningStartHour: 20,
    eveningStartMinute: 30,
  },
  {
    timezone: 'Australia/Sydney',
    startHour: 10,
    endHour: 17,
    durationMinutes: 30,
    eveningStartHour: 20,
    eveningStartMinute: 30,
  },
  {
    timezone: 'Africa/Johannesburg',
    startHour: 10,
    endHour: 17,
    durationMinutes: 30,
    eveningStartHour: null,
    eveningStartMinute: null,
  },
];
